const fs = require('fs');
const isEqual = require('lodash/isEqual');

const { createFile } = require('../utils/files');
const { toOpenApiSchema } = require('../utils/schemas');
const { testsResponsesToDocumentation } = require('../utils/mappers');

const DOCS_DIR = 'swagger_docs';
const FILE_TYPE = 'json';

exports.gendocs = request => {
  const data = testsResponsesToDocumentation(request);
  // console.log(data);
  const path = `${DOCS_DIR}${data.path}`;
  const dirPath = `${process.cwd()}/${path}`;
  const filePath = `${dirPath}${data.method}.${FILE_TYPE}`;
  const schemas = toOpenApiSchema(data.resBody);

  const documentation = {
    components: {
      schemas: schemas.properties
    }
  };

  documentation[`${data.path}`] = {};
  documentation[`${data.path}`][`${data.method.toLowerCase()}`] = {};
  documentation[`${data.path}`][`${data.method.toLowerCase()}`].tags = [];
  documentation[`${data.path}`][`${data.method.toLowerCase()}`].summary = '';
  documentation[`${data.path}`][`${data.method.toLowerCase()}`].description = '';
  documentation[`${data.path}`][`${data.method.toLowerCase()}`].operationId = '';
  documentation[`${data.path}`][`${data.method.toLowerCase()}`].parameters = [];
  documentation[`${data.path}`][`${data.method.toLowerCase()}`].responses = {};

  if (fs.existsSync(filePath)) {
    const file = JSON.parse(fs.readFileSync(filePath, 'utf8'));

    if (isEqual(file, documentation)) {
      // When the test data is not self-generated by any faker,
      // the response will be exactly the same.
      // In this case there is nothing to do
    } else {
      createFile(dirPath, filePath, JSON.stringify(documentation));
      console.log('file created successfully');
    }
    return;
  }

  createFile(dirPath, filePath, JSON.stringify(documentation));
  console.log('file created successfully');
};
